language: node_js
node_js:		
  - "6.7.0"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
branches:
  only: master
script:
  - npm run lint
  # - npm test
  - npm run build
after_script:
  - make publish
  - cp index.js ./publish/
  - cd publish
  - git init
  - git config user.name "cnaspx"
  - git config user.email "feelsky@163.com"
  - git add .
  - git commit -m "Travis build"
  - git push  --force --quiet "https://${GH_TOKEN}@github.com/cnaspx/vue-baidu-map.git" master:publish
